### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by Demivan** [Demivan/fluent-vue#10]
Add usage examples and features description

**Comment by tobyzerner** [comment]
Hi @Demivan! I'm currently searching for a Fluent Vue integration. Do you think you'll be able to add some usage instructions soon?

**Comment by Demivan** [comment]
Hi @tobyzerner. I have merged #25 with updated readme and example project.
I would not recommend using this project in production just yet. I'm currently integrating it with my work project and fixing issues as I encounter them.
But I would greatly appreciate if you want to try it out and report usage issues and bugs if you encounter them.

**Comment by tobyzerner** [comment]
Thanks @Demivan, that's very helpful. I have a few questions:

1. What are your thoughts about the [`Localized` component API](https://github.com/projectfluent/fluent.js/wiki/React-Tutorial#localizing-content) in the official React integration? Is there any reason you haven't tried to replicate that API here? (There is [another](https://github.com/texthtml/vue-fluent) Vue/Fluent integration in its early stages which does)

2. With your API, is there any equivalent of the [overlays feature](https://github.com/projectfluent/fluent.js/wiki/React-Overlays)?

3. Is there any way to use the `$t` method outside of a Vue component? From a quick look at the code I guess it would be `fluent.format(key, args)` (where `fluent` is the `FluentVue` instance)?

**Comment by Demivan** [comment]
I have based API of this library on https://github.com/kazupon/vue-i18n. I'm currently using `vue-i18n` and wanted API to be mostly compatible. I'm thinking of implementing both `vue-i18n` and `fluent-react` APIs in the future. 

1. I just haven't tried implementing it yet. I'm up for adding that functionality, it could simplify binding translations to Vue components.
`v-t` directive currently is enough for me - it works like `Localized` component when used on regular DOM nodes and is less verbose.

2. `i18n` component does similar thing. It is based on [vue-i18n](https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage) `i18n` component. It doesn't translate child components though.

3. Yeah, `fluent.format(key, args)` is the way to go. In my project I have just exported function `$t` that calls `fluent.format` so I don't have `fluent` instance imported everywhere. I should add that to README.

**Comment by tobyzerner** [comment]
Ah I see, makes sense. Thanks for the info :)
