### ISSUE TITLE
Change locale bundles after mounted?

### ISSUE THREAD

**Issue by hongquan** [Demivan/fluent-vue#662]
Hi @Demivan ,

Currently, the language to display is chosen by the order of bundles passed to `createFluentVue`. This is done before Vue app is mounted.

Is there any way to change language after the app is mounted, like when jumping to a page via vue-router?

**Comment by Demivan** [comment]
Hi @hongquan.

Thanks for taking interest in my library :)

To change language you need to re-assign `bundles` property to new list of bundles that you want. Changing bundles list will automatically re-render components that use translations.

```js
const enBundle = new FluentBundle('en')
const ukBundle = new FluentBundle('uk')

// Default language - English
const fluent = createFluentVue({
  bundles: [enBundle]
})

// Change language to Ukrainian
fluent.bundles = [ukBundle]
```

Documentation for this is currently missing. I'm going to add it to documentation site today.

**Comment by hongquan** [comment]
Thanks @Demivan 

It means that I just need to define `fluent` in some source file, then import to component vue file?

**Comment by Demivan** [comment]
Pretty much. You can export plugin instance returned from `createFluentVue` from the file where you configured it.
Or create helper function that changes locale and export it for convenience.

```js
export function changeLocale(locale) {
  // getBundlesForLocale - your logic for choosing bundle order
  fluent.bundles = getBundlesForLocale(locale)
}
```

I may add composition api method to change locale for convenience.

**Comment by Demivan** [comment]
Looked into creating composition api. It does not really make sense to implement it, as you need to have access to all your defined bundles anyway for it to work.

So to sum up:
`translations.js`
```js
const enBundle = new FluentBundle('en')
const ukBundle = new FluentBundle('uk')

export const fluent = createFluentVue({
  bundles: [enBundle]
})

export function changeLocale (locale) {
  fluent.bundles = // Your logic for getting bundle order
}
```

`index.js`
```js
import { createApp } from 'vue'
import { fluent } from '@/translations.js'

createApp(App)
  .use(fluent)
  .mount('#root')
```

`LocalePicker.vue`
```js
import { changeLocale } from '@/translations.js'
// Use changeLocale to change locale :)
```

**Comment by hongquan** [comment]
Thanks, @Demivan
