### ISSUE TITLE
Import translation from external FLT file

### ISSUE THREAD

**Issue by hongquan** [Demivan/fluent-vue#664]
Hi @Demivan 

Currently, the usage is to add a block to .vue file:

```vue
<fluent locale='en'>
</fluent>
```

Is there any way that I just write those fluent translations in external .ftl files, then import into .vue file? That way, I can give .ftl files to translator team to do their job, then get back the result. The .vue file with so much code will scare them.

**Comment by Demivan** [comment]
You can add translations directly to the bundle:

```js
import { FluentBundle, FluentResource } from '@fluent/bundle'

import enTranslations from '@/translations/en.ftl'

const enBundle = new FluentBundle('en')
enBundle.addResource(new FluentResource(enTranslations))
```

You may need to configure you build system to allow importing ftl files. For `webpack` just use `raw-loader` (asset/source).  
Downside of this approach is that translations are not code-split with components.

For my project I use custom scripts that extract or import `<fluent>` tag content and convert it to or from resx file. But script is not really portable. I have plans on implementing CLI tool to extract/import `<fluent>` tag content.

**Comment by hongquan** [comment]
Thanks, @Demivan

I'm using Vite. It may have something similar to Webpack's `raw-loader`.
