### ISSUE TITLE
Public facing website link described in the docs is broken

### ISSUE THREAD

**Issue by erickwilder** [Demivan/fluent-vue#708]
Hello,

While browsing the project docs I noticed that the main public-facing website link listed in the README file is broken:

https://fluent-vue.demivan.me/

**Comment by Demivan** [comment]
Hi, thanks for the heads up.

Looks like DNS is not fully propagated for some reason. Will check what can I do to fix this.

**Comment by Demivan** [comment]
@erickwilder Can you check if it works on your end now?

**Comment by Demivan** [comment]
Dns checker reports that everything is ok now. Thanks again for reporting this.

**Comment by erickwilder** [comment]
Hello @Demivan 

My apologies for the late reply and interestingly, it _was working_ and it doesn't work again. Perhaps you have some piece of automation that rolled back your changes in place?

**Comment by Demivan** [comment]
Thank you for contacting me again. Looks like it is back up. Can you confirm?
I don't have any DNS automation. It is just Github pages and Namecheap DNS.

If this happens again I will probably just switch from Namecheap.
