### ISSUE TITLE
Easier way to set attribute directly?

### ISSUE THREAD

**Issue by fipp** [Demivan/fluent-vue#772]
First of all, great project! Your blog post about [vue-i18n](https://demivan.me/posts/2021-08-08-vue-i18n-in-real-world-application.html) resonates.  

But I wonder if it's a way to set attributes more directly. Let's say I have this image where I want to localize the alt text:
`<img :src="logo" alt="Logo of company X" />`

As I understand it, I can do:
```
<img :src="logo" v-bind="$ta('logo')" />
```

And have a `.ftl` definition of:
```
logo =
  .alt = Logo of company X
```

Is it possible to set it more directly? In `vue-i18n-next` I can reference the language tag directly:

```
<img :src="logo" :alt="t('logoAltText')" />
```

As I understand it, this is not supported now, or maybe it is? If not, do you think it could be? I see the `$ta` pattern great for translating two or more attributes, but if there is only one, it would be nice to reference the language tag directly?

Again thank you for your work!

**Comment by fipp** [comment]
d'oh, i'm stupid. don't know why I didn't realize, but I can already do this:
```
<img :src="logo" v-bind="$t('logoAltText')" />
```

**Comment by Demivan** [comment]
I'm curious to know, how did you find the project?

**Comment by fipp** [comment]
By googling "fluent vue" or "vue fluent" I believe :) 

I asked around at my company's slack channel for tips about i18n, and another team recommended me projectfluent with weblate as localization tool. So far so good!

**Comment by Demivan** [comment]
By the way there is a Pontoon project by Mozilla. If you need a self-hosted alternative to Weblate

**Comment by Demivan** [comment]
@oliverpool I'm curious, why not use `v-t` directive in this case?

I could modify `$ta` with an additional parameter that specifies allowlist of attributes, so it could be used with v-bind.

**Comment by oliverpool** [comment]
I just had a case where I wanted to bind on a custom component (custom tooltip, like `<abbr title="...">text</abbr>`): `v-t` does not work and `v-bind="$ta(...)"` can be dangerous.

So I think that `:my-prop="$ta(...).myprop"` is the best for now (and is probably enough).

**Comment by Demivan** [comment]
@oliverpool Thanks for explanation. What do you think about adding `$ta('key', allowedAttrsArray)`? Worth adding this functionality for such cases?

**Comment by oliverpool** [comment]
> Worth adding this functionality for such cases?

I am not sure. I don't need it right now, so I would advise to wait for more feedback.
