### ISSUE TITLE
Feature request, missing translations checker?

### ISSUE THREAD

**Issue by fipp** [Demivan/fluent-vue#773]
Hi! Would it be possible with a npm script of some kind (linter?) to check for missing translations? To e.g. be able to say that "all translation string in `en.ftl` should be present in all the other translation files"?

**Comment by Demivan** [comment]
That particular check, I think, should be a part of your localization tool.

Pontoon has this: 
![image](https://user-images.githubusercontent.com/2339406/173034797-01acff5a-7e64-4c93-9aa7-49974da3cd9c.png)

"i18n Ally" VS Code extension has this too.

I was planning to create an ESLint plugin #743. One rule would be to check that key used in a component is present in your base translation file. But I did not have time to work on it yet.

**Comment by fipp** [comment]
Yeah that makes sense! closing this then.
